osx_image: xcode10.2
dist: bionic

language: node_js
node_js: '10'

addons:
  apt:
    packages:
      - xvfb

matrix:
  include:
    - if: branch =~ /v\d+\.\d+\.\d+/
      os: windows
    - if: branch =~ /v\d+\.\d+\.\d+/
      os: osx
    - os: linux

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
    - .next/cache

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install -g xvfb-maybe
  - npm ci

before_script:
  - if [[ "$TRAVIS_TAG" != "" ]]; then npm --no-git-tag-version version ${TRAVIS_TAG:1}; fi

script:
  - npm run lint
  - npm run build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-maybe npm run e2e; fi

  - echo "Build win"
  - if [[ "$TRAVIS_OS_NAME" == "windows" && "$TRAVIS_TAG" != "" ]]; then npm run dist:win; fi

  - echo "Build mac"
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_TAG" != "" ]]; then npm run dist:mac; fi

  - echo "Build linux"
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_TAG" != "" ]]; then npm run dist:linux; fi
